import { useEffect, useState } from 'react';
import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import { Section } from '@/stores/projectStore';
import { useProjectStore } from '@/stores/projectStore';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import {
  Bold,
  Italic,
  List,
  ListOrdered,
  Heading2,
  Quote,
  Code,
  Undo,
  Redo,
  Sparkles,
  Loader2,
} from 'lucide-react';
import { toast } from 'sonner';
import api from '@/lib/api';
import { useAuthStore } from '@/stores/authStore';
import { cn } from '@/lib/utils';

interface EditorPanelProps {
  projectId: string;
  section: Section;
}

export const EditorPanel = ({ projectId, section }: EditorPanelProps) => {
  const updateSection = useProjectStore((state) => state.updateSection);
  const addRevision = useProjectStore((state) => state.addRevision);
  const [isGenerating, setIsGenerating] = useState(false);
  const token = useAuthStore.getState().token;
  const currentProject = useProjectStore((s) => s.currentProject);
  // default to preview mode for PPTX projects
  const defaultPreview = currentProject?.docType === 'pptx';
  const [showPreview, setShowPreview] = useState<boolean>(!!defaultPreview);

  const editor = useEditor({
    extensions: [StarterKit],
    content: section.content || '<p>Click "Generate Content" to start...</p>',
    editorProps: {
      attributes: {
        class: 'prose prose-sm max-w-none focus:outline-none min-h-[500px] p-6',
      },
    },
    onUpdate: ({ editor }) => {
      updateSection(projectId, section.id, { content: editor.getHTML() });
    },
  });

  useEffect(() => {
    if (editor && section.content !== editor.getHTML()) {
      editor.commands.setContent(section.content || '<p>Click "Generate Content" to start...</p>');
    }
  }, [section.id, section.content, editor]);

  const handleGenerate = () => {
    (async () => {
      setIsGenerating(true);
      try {
        if (!token) {
          toast.error('You must be logged in to generate content.');
          setIsGenerating(false);
          return;
        }
        const res = await api.post(`/api/projects/${projectId}/generate`, { sectionId: section.id });
        const out = res.data as any;
        const text = out.text || '<p>(no content returned)</p>';
        editor?.commands.setContent(text);
        updateSection(projectId, section.id, { content: text });
        // persist a local revision entry as well as update store
        addRevision(projectId, section.id, { content: text, prompt: 'AI generate' });
        toast.success('Content generated by AI');
      } catch (e) {
        console.error('Generate failed', e);
        toast.error('Failed to generate content');
      } finally {
        setIsGenerating(false);
      }
    })();
  };

  if (!editor) {
    return null;
  }

  return (
    <div className="h-full flex flex-col">
      {/* Toolbar */}
      <div className="border-b bg-card/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="p-4 space-y-3">
          <div className="flex items-center space-x-1">
            <Button
              variant="ghost"
              size="sm"
              onClick={() => editor.chain().focus().toggleBold().run()}
              className={cn(editor.isActive('bold') && 'bg-accent')}
            >
              <Bold className="w-4 h-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => editor.chain().focus().toggleItalic().run()}
              className={cn(editor.isActive('italic') && 'bg-accent')}
            >
              <Italic className="w-4 h-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => editor.chain().focus().toggleHeading({ level: 2 }).run()}
              className={cn(editor.isActive('heading', { level: 2 }) && 'bg-accent')}
            >
              <Heading2 className="w-4 h-4" />
            </Button>
            <Separator orientation="vertical" className="h-6 mx-1" />
            <Button
              variant="ghost"
              size="sm"
              onClick={() => editor.chain().focus().toggleBulletList().run()}
              className={cn(editor.isActive('bulletList') && 'bg-accent')}
            >
              <List className="w-4 h-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => editor.chain().focus().toggleOrderedList().run()}
              className={cn(editor.isActive('orderedList') && 'bg-accent')}
            >
              <ListOrdered className="w-4 h-4" />
            </Button>
            <Separator orientation="vertical" className="h-6 mx-1" />
            <Button
              variant="ghost"
              size="sm"
              onClick={() => editor.chain().focus().toggleBlockquote().run()}
              className={cn(editor.isActive('blockquote') && 'bg-accent')}
            >
              <Quote className="w-4 h-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => editor.chain().focus().toggleCodeBlock().run()}
              className={cn(editor.isActive('codeBlock') && 'bg-accent')}
            >
              <Code className="w-4 h-4" />
            </Button>
            <Separator orientation="vertical" className="h-6 mx-1" />
            <Button
              variant="ghost"
              size="sm"
              onClick={() => editor.chain().focus().undo().run()}
              disabled={!editor.can().undo()}
            >
              <Undo className="w-4 h-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => editor.chain().focus().redo().run()}
              disabled={!editor.can().redo()}
            >
              <Redo className="w-4 h-4" />
            </Button>
          </div>
          
          <Button onClick={handleGenerate} className="w-full" size="sm" disabled={isGenerating}>
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4 mr-2" />
                Generate Content with AI
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Editor Content */}
      <div className="flex-1 overflow-y-auto bg-background">
        {/* For PPTX projects, allow previewing the slide in a canvas-like frame */}
        {currentProject?.docType === 'pptx' ? (
          <div className="p-6">
            <div className="mb-3 flex items-center space-x-2">
              <Button size="sm" variant={showPreview ? 'secondary' : 'ghost'} onClick={() => setShowPreview(true)}>Preview</Button>
              <Button size="sm" variant={!showPreview ? 'secondary' : 'ghost'} onClick={() => setShowPreview(false)}>Edit</Button>
            </div>
            {showPreview ? (
              <div className="w-full flex justify-center">
                <div className="bg-white shadow-lg" style={{ width: 1024, height: 576 }}>
                  <div style={{ width: '100%', height: '100%', padding: 28, boxSizing: 'border-box', overflow: 'auto' }}>
                    <div dangerouslySetInnerHTML={{ __html: section.content || '<h2>Empty Slide</h2>' }} />
                  </div>
                </div>
              </div>
            ) : (
              <EditorContent editor={editor} className="h-full" />
            )}
          </div>
        ) : (
          <EditorContent editor={editor} className="h-full" />
        )}
      </div>
    </div>
  );
};
